# Dockerfile
FROM bde2020/hadoop-docker:2.0.0-hadoop3.2.1-java8

# Optional: create directories inside container for Spark streaming
RUN mkdir -p /data/weather/marrakesh
RUN mkdir -p /data/weather/checkpoint
